const ShopActionTypes = {
  FETCH_SHOP_DATA: "FETCH_SHOP_DATA",
  FETCH_COLLECTION_START: "FETCH_COLLECTION_START",
  FETCH_COLLECTION_SUCCESS: "FETCH_COLLECTION_SUCCESS",
  FETCH_COLLECTION_FAILED: "FETCH_COLLECTION_FAILED",
};

export default ShopActionTypes;
